const CART_TYPES = {
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  TOGGLE_CART_VISIBILITY: 'TOGGLE_CART_VISIBILITY',
  INCREASE_ITEM_QUANTITY: 'INCREASE_ITEM_QUANTITY',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
};

export default CART_TYPES;
